spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
---
spring:
  config.activate.on-profile: h2-test
  datasource:
    platform: mysql
    hikari:
      jdbc-url: jdbc:h2:mem:test_db;MODE=MySql
    username: sa
    password:
  test.database.replace: none
  sql.init.mode: never
---
spring:
  config.activate.on-profile: mysql-local
  datasource:
    url: jdbc:mysql://localhost:3306/porko?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: porko-local
    password: porko-local-pw
