spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
---
spring:
  config.activate.on-profile: h2-test
  datasource:
    platform: mysql
    hikari:
      jdbc-url: ${datasource.url}
    username: ${datasource.username}
    password:
  test.database.replace: none
  sql.init.mode: never
---
spring:
  config.activate.on-profile: mysql-local
  datasource:
    url: ${datasource.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${datasource.username}
    password: ${datasource.password}
