spring:
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/port.yml
      - classpath:properties/jwt.yml
      - classpath:properties/logging.yml
      - classpath:properties/sql-init.yml
      - classpath:properties/p6spy.yml
  profiles:
    group:
      test: h2-test, jpa-test
      local: port-local, jwt-local, logging-local, sql-init-local, p6spy-local, mysql-local, jpa-local
