spring:
  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
  profiles:
    group:
      test: h2-test, jpa-test
      local: mysql-local, jpa-local, p6spy-local, logging-local
